from datetime import datetime, timezone
import pyodbc
SQL="""SELECT TOP 20 CONVERT(bigint,qs.query_hash),CONVERT(bigint,qs.query_plan_hash),qs.execution_count,qs.total_elapsed_time,qs.total_worker_time,qs.total_logical_reads,qs.total_logical_writes,qs.total_physical_reads,qs.last_elapsed_time,qs.last_worker_time,qs.last_logical_reads,qs.last_logical_writes,qs.min_elapsed_time,qs.max_elapsed_time,qs.total_elapsed_time/NULLIF(qs.execution_count,0),qs.total_worker_time/NULLIF(qs.execution_count,0),qs.total_logical_reads/NULLIF(qs.execution_count,0),DB_NAME(st.dbid),SUBSTRING(st.text,(qs.statement_start_offset/2)+1,((CASE qs.statement_end_offset WHEN -1 THEN DATALENGTH(st.text) ELSE qs.statement_end_offset END-qs.statement_start_offset)/2)+1),CONVERT(varchar(128),qs.sql_handle,2),CONVERT(varchar(128),qs.plan_handle,2) FROM sys.dm_exec_query_stats qs CROSS APPLY sys.dm_exec_sql_text(qs.sql_handle) st ORDER BY qs.total_worker_time DESC"""
def collect_query_metrics(conn,run_key,instance_key):
    cur=conn.cursor();cur.execute(SQL);now=datetime.now(timezone.utc);out=[]
    for r in cur.fetchall():
        if not r[17]: continue
        out.append({'collection_run_key':run_key,'instance_key':instance_key,'collected_at':now,'query_hash':r[0],'query_plan_hash':r[1],'execution_count':int(r[2] or 0),'total_elapsed_ms':float((r[3] or 0)/1000.0),'total_cpu_ms':float((r[4] or 0)/1000.0),'total_logical_reads':int(r[5] or 0),'total_logical_writes':int(r[6] or 0),'total_physical_reads':int(r[7] or 0),'last_elapsed_ms':float((r[8] or 0)/1000.0),'last_cpu_ms':float((r[9] or 0)/1000.0),'last_logical_reads':int(r[10] or 0),'last_logical_writes':int(r[11] or 0),'min_elapsed_ms':float((r[12] or 0)/1000.0),'max_elapsed_ms':float((r[13] or 0)/1000.0),'avg_elapsed_ms':float((r[14] or 0)/1000.0),'avg_cpu_ms':float((r[15] or 0)/1000.0),'avg_logical_reads':float(r[16] or 0),'database_name':r[17],'query_text':r[18],'sql_handle':r[19],'plan_handle':r[20],'status':'success'})
    return out
