apiVersion: 1
datasources:
  - name: Monitoring PostgreSQL
    uid: monitoring-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: $__env{POSTGRES_USER}
    secureJsonData:
      password: $__env{POSTGRES_PASSWORD}
    jsonData:
      database: $__env{POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: false
