apiVersion: 1

datasources:
  - name: Monitoring PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: monitoring_db
    user: postgres
    secureJsonData:
      password: 123456
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
