{
 "title": "sql server monitoring dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last SQL Server Data Capture",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(captured_at) AS \"Last Capture Time\" FROM fct_sql_metrics;"
    }
   ]
  },
  {
   "title": "Data Freshness Delay",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  EXTRACT(EPOCH FROM (NOW() - MAX(captured_at))) / 60 AS \"Delay Minutes\" FROM fct_sql_metrics;"
    }
   ]
  },
  {
   "title": "Total Metric Records",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    COUNT(*) AS \"Total Records\"\r\nFROM fct_sql_metrics\r\nWHERE $__timeFilter(captured_at);"
    }
   ]
  },
  {
   "title": "Database Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    metric_value AS \"Database Count\"\r\nFROM fct_sql_metrics\r\nWHERE metric_name = 'database_count'\r\nORDER BY captured_at DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Online Database Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    metric_value AS \"Online Database Count\"\r\nFROM fct_sql_metrics\r\nWHERE metric_name = 'database_online_count'\r\nORDER BY captured_at DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "SQL Server Metrics Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    captured_at AS \"time\",\r\n    metric_name AS metric,\r\n    metric_value AS value\r\nFROM fct_sql_metrics\r\nWHERE $__timeFilter(captured_at)\r\nORDER BY captured_at;\r\n"
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    captured_at AS \"time\",\r\n    metric_value AS \"User Connections\"\r\nFROM fct_sql_metrics\r\nWHERE $__timeFilter(captured_at)\r\n  AND metric_name = 'user_connection_count'\r\nORDER BY captured_at;\r\n"
    }
   ]
  },
  {
   "title": "SQL Server Committed Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    captured_at AS \"time\",\r\n    metric_name AS metric,\r\n    metric_value AS value\r\nFROM fct_sql_metrics\r\nWHERE $__timeFilter(captured_at)\r\n  AND metric_name IN (\r\n      'sqlserver_committed_memory_mb',\r\n      'sqlserver_committed_target_memory_mb'\r\n  )\r\nORDER BY captured_at;"
    }
   ]
  },
  {
   "title": "SQL Server Physical Memory MB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    captured_at AS \"time\",\r\n    metric_value AS \"Physical Memory MB\"\r\nFROM fct_sql_metrics\r\nWHERE $__timeFilter(captured_at)\r\n  AND metric_name = 'sqlserver_physical_memory_mb'\r\nORDER BY captured_at;"
    }
   ]
  },
  {
   "title": "Latest Metric Values",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (instance_name, metric_name)\r\n    instance_name,\r\n    metric_name,\r\n    metric_value,\r\n    metric_unit,\r\n    captured_at\r\nFROM fct_sql_metrics\r\nWHERE $__timeFilter(captured_at)\r\nORDER BY\r\n    instance_name,\r\n    metric_name,\r\n    captured_at DESC;\r\n"
    }
   ]
  }
 ]
}